# Generated by Django 5.1.6 on 2025-02-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netlify_movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='netlify_movies',
            new_name='Netflix',
        ),
        migrations.AlterModelOptions(
            name='netflix',
            options={'verbose_name_plural': 'Netflix netlify_project'},
        ),
    ]
