# Generated by Django 5.1.6 on 2025-02-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netlify_movies', '0002_rename_netlify_movies_netflix_alter_netflix_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netflix',
            options={'verbose_name_plural': 'Netflix'},
        ),
    ]
