# Generated by Django 5.1.6 on 2025-02-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netlify_movies', '0003_alter_netflix_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflix',
            name='description',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
