# Generated by Django 5.1.6 on 2025-02-17 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netlify_movies', '0004_alter_netflix_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflix',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='netflix',
            name='movie_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
