# Generated by Django 5.1.6 on 2025-02-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netlify_movies', '0005_alter_netflix_description_alter_netflix_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflix',
            name='movie_name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
