# Generated by Django 5.1.6 on 2025-02-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netlify_movies', '0006_alter_netflix_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='netflix',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
